/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode.app;

import leetcode.list.LinkedList;

import static leetcode.utilities.StringUtils.join;
import static leetcode.utilities.StringUtils.split;
import static leetcode.app.MessageUtils.getMessage;

import leetcode.utilities.*;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
//        LinkedList tokens;
//        tokens = split(getMessage());
//        String result = join(tokens);
//        System.out.println(WordUtils.capitalize(result));

        int[] gas = {1,2,3};
        int[] cost = {4,4,1,5,1};
//        int[] heights= {2,8,5,5,6,1,7,4,5};
//        int[] heights= {8,9,3,6,9,6,8,0,7,6,8,1};
//        int[] heights= {1,9,7,1,3,6,4,7,4,8,3,6,3,5,3,7};
//        int[] heights= {0,1,0,2,1,0,1,3,2,1,2,1};
        int[][] heights= {{9,12},{1,10},{4,11},{8,12},{3,9},{6,9},{6,7}};
        String string = "MCMXCIV";
        String[] test = {"acc","aaa","aaba"};
        String a = "sadbutsad";
        String b = "sad";

        AV av = new AV();
        System.out.println(av.trailingZeroes(7));
    }
}
