/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode.app;

import leetcode.list.LinkedList;

import static leetcode.utilities.StringUtils.join;
import static leetcode.utilities.StringUtils.split;
import static leetcode.app.MessageUtils.getMessage;

import leetcode.utilities.J;
import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
//        LinkedList tokens;
//        tokens = split(getMessage());
//        String result = join(tokens);
//        System.out.println(WordUtils.capitalize(result));
//        int[] ary1 = {7,1,5,3,6};
        int[] ary1 = {1,1,1,1,1};

        System.out.println(J.jump(ary1));

        for(int a: ary1){
            System.out.print(a + " ");
        }
    }
}
